name: Build and Deploy
on:
  push:
    branches:
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:

    - name: Checkout
      uses: actions/checkout@v1

    - name: Build
      env:
        REACT_APP_TOKEN: ${{ secrets.REACT_APP_TOKEN }}
      run: |
        npm install
        npm run-script build
      
    
    - name: Deploy
      uses: JamesIves/github-pages-deploy-action@releases/v2
      with:
          GITHUB_TOKEN: ${{ secrets.REACT_APP_TOKEN }}
          BRANCH: gh-pages
          FOLDER: build
